# Generated by Django 4.2.27 on 2026-01-24 23:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('skill_level', models.CharField(choices=[('C-', 'C-'), ('C', 'C'), ('C+', 'C+'), ('B-', 'B-'), ('B', 'B'), ('B+', 'B+')], max_length=2)),
                ('max_teams', models.PositiveIntegerField()),
                ('registration_deadline', models.DateTimeField()),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('captain_name', models.CharField(max_length=100)),
                ('captain_email', models.EmailField(max_length=254)),
                ('captain_phone', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('WAITLIST', 'Waitlist')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament')),
            ],
        ),
    ]
